# ESPHome top-level section keys and UI categories for the section-based Components panel.
# See docs/ESPHOME_TOP_LEVEL_KEYS.md.

# Canonical order for emitting YAML (compile output). Only sections with content are emitted.
SECTION_ORDER: tuple[str, ...] = (
    # Device & platform
    "esphome",
    "esp32",
    "esp8266",
    "rp2040",
    "libretiny",
    "host",
    "nrf52",
    "esp32_hosted",
    "psram",
    "esp_ldo",
    "deep_sleep",
    "preferences",
    # Configuration
    "packages",
    "substitutions",
    "external_components",
    # Network
    "wifi",
    "ethernet",
    "openthread",
    "network",
    "api",
    "ota",
    "logger",
    "mdns",
    "captive_portal",
    "web_server",
    "mqtt",
    "espnow",
    "http_request",
    "wireguard",
    "statsd",
    "udp",
    "packet_transport",
    "zigbee",
    # Bluetooth
    "esp32_ble_beacon",
    "ble_client",
    "esp32_ble_tracker",
    "esp32_ble_server",
    "bluetooth_proxy",
    "ble_nus",
    "esp32_improv",
    "improv_serial",
    # Busses & interfaces
    "one_wire",
    "canbus",
    "i2c",
    "spi",
    "uart",
    "i2s_audio",
    "opentherm",
    "tinyusb",
    "usb_cdc_acm",
    "usb_host",
    "usb_uart",
    # Display & touch
    "display",
    "touchscreen",
    "font",
    "image",
    "graph",
    "qr_code",
    "animation",
    "online_image",
    "display_menu",
    "output",
    "light",
    "lvgl",
    # Automation & logic
    "globals",
    "interval",
    "time",
    "script",
    "json",
    "mapping",
    "xxtea",
    "copy",
    "demo",
    "factory_reset",
    "event",
    # Sensors & entities
    "sensor",
    "text_sensor",
    "binary_sensor",
    "switch",
    "button",
    "number",
    "select",
    "lock",
    "cover",
    "fan",
    "climate",
    "media_player",
    "alarm_control_panel",
    "datetime",
    "valve",
    "water_heater",
    "text",
    # Audio
    "audio_adc",
    "audio_dac",
    "microphone",
    "speaker",
    # Debug & monitoring
    "debug",
    "syslog",
    "prometheus",
    "safe_mode",
    "esp32_camera_web_server",
    "update",
    # I/O expanders
    "ch422g",
    "ch423",
    "max6956",
    "mcp230xx",
    "pca6416a",
    "pca9554",
    "pcf8574",
    "pi4ioe5v6408",
    "sn74hc165",
    "sn74hc595",
    "sx1509",
    "tca9548a",
    "tca9555",
    "weikai",
    "xl9535",
    # Other
    "infrared",
    "remote_receiver",
    "remote_transmitter",
    "rf_bridge",
    "modbus_controller",
    "esp32_camera",
    "gps",
    "sun",
    "tuya",
    "power_supply",
    "servo",
    "stepper",
    "matrix_keypad",
    "rtttl",
    "sml",
    "vbus",
    "sprinkler",
    "status_led",
    "key_collector",
    "fingerprint_grow",
    "hlk_fm22x",
    "exposure_notifications",
    "zwave_proxy",
    "cc1101",
    "sim800l",
    "sx126x",
    "sx127x",
    "ezo_pmp",
    "grove_tb6612fng",
    "lightwaverf",
    "micronova",
    "pipsolar",
    "uponor_smatrix",
    "sun_gtil2",
    "at581x",
    "dfrobot_sen0395",
    "pn7150",
    "pn7160",
    "wiegand",
    "ir_rf_proxy",
    "micro_wake_word",
    "voice_assistant",
    "dfplayer",
    "emc2101",
    "seeed_mr60bha2",
    "seeed_mr60fda2",
    "seeed_mr24hpc1",
    "pylontech",
)

# UI categories: label -> list of section keys (order preserved for panel).
SECTION_CATEGORIES: dict[str, tuple[str, ...]] = {
    "Device & platform": (
        "esphome", "esp32", "esp8266", "rp2040", "libretiny", "host", "nrf52",
        "esp32_hosted", "psram", "esp_ldo", "deep_sleep", "preferences",
    ),
    "Configuration": ("packages", "substitutions", "external_components"),
    "Network": (
        "wifi", "ethernet", "openthread", "network", "api", "ota", "logger",
        "mdns", "captive_portal", "web_server", "mqtt", "espnow", "http_request",
        "wireguard", "statsd", "udp", "packet_transport", "zigbee",
    ),
    "Bluetooth": (
        "esp32_ble_beacon", "ble_client", "esp32_ble_tracker", "esp32_ble_server",
        "bluetooth_proxy", "ble_nus", "esp32_improv", "improv_serial",
    ),
    "Busses & interfaces": (
        "one_wire", "canbus", "i2c", "spi", "uart", "i2s_audio", "opentherm",
        "tinyusb", "usb_cdc_acm", "usb_host", "usb_uart",
    ),
    "Display & touch": (
        "display", "touchscreen", "font", "image", "graph", "qr_code",
        "animation", "online_image", "display_menu", "output", "light", "lvgl",
    ),
    "Automation & logic": (
        "globals", "interval", "time", "script", "json", "mapping", "xxtea",
        "copy", "demo", "factory_reset", "event",
    ),
    "Sensors & entities": (
        "sensor", "text_sensor", "binary_sensor", "switch", "button", "number",
        "select", "lock", "cover", "fan", "climate", "media_player",
        "alarm_control_panel", "datetime", "valve", "water_heater", "text",
    ),
    "Audio": ("audio_adc", "audio_dac", "microphone", "speaker"),
    "Debug & monitoring": (
        "debug", "logger", "syslog", "prometheus", "safe_mode",
        "web_server", "esp32_camera_web_server", "update",
    ),
    "I/O expanders": (
        "ch422g", "ch423", "max6956", "mcp230xx", "pca6416a", "pca9554",
        "pcf8574", "pi4ioe5v6408", "sn74hc165", "sn74hc595", "sx1509",
        "tca9548a", "tca9555", "weikai", "xl9535",
    ),
    "Other": (
        "infrared", "remote_receiver", "remote_transmitter", "rf_bridge",
        "modbus_controller", "esp32_camera", "gps", "sun", "tuya", "power_supply",
        "servo", "stepper", "matrix_keypad", "rtttl", "sml", "vbus", "sprinkler",
        "status_led", "key_collector", "fingerprint_grow", "hlk_fm22x",
        "exposure_notifications", "zwave_proxy", "cc1101", "sim800l", "sx126x",
        "sx127x", "ezo_pmp", "grove_tb6612fng", "lightwaverf", "micronova",
        "pipsolar", "uponor_smatrix", "sun_gtil2", "at581x", "dfrobot_sen0395",
        "pn7150", "pn7160", "wiegand", "ir_rf_proxy", "micro_wake_word",
        "voice_assistant", "dfplayer", "emc2101", "seeed_mr60bha2",
        "seeed_mr60fda2", "seeed_mr24hpc1", "pylontech",
    ),
}
